
brpc:
  application-name: 'bobby-app'
  zk:
    address: 192.168.160.128:2181
    session-timeout-ms: 30000  # 必须使用中划线
    retry:
      base-sleep-time-ms: 1000 # 嵌套属性同样规则
      max-retries: 3
  netty:
    port: 8090